### ISSUE TITLE
delete product button is broken

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver_app#310]
Trocando o responsável aqui @jandsonrj -> @crisingulani, agora a missão aqui é apenas entender o motivo do produto estar com URL igual a None (vide mensagem de erro abaixo) para evitar casos assim no futuro. @crisingulani Depois que der uma olhada aqui pode fechar o issue e marcar como Done.   

https://github.com/user-attachments/assets/226ccfb3-ef39-4407-8f9f-b1e3e59fa6b6

**Comment by jandsonrj** [comment]
I conducted tests in both my local development environment and the staging environment (the same one used in your example video). I also reviewed the 'ProductRemove' code responsible for this function, and I didn’t find any issues. To demonstrate the functionality, I created a video showing both environments. You can access it by clicking [here](https://www.youtube.com/watch?v=m1bU5HKwLy8)

**Comment by gschwend** [comment]
@jandsonrj the problem persists for my user, let's investigate further

**Comment by jandsonrj** [comment]
> @jandsonrj the problem persists for my user, let's investigate further

In a conversation I had with @glaubervila , he mentioned that it would be necessary to check the server logs when the error occurs. What do you think about setting up a call to try to capture the error with the logs open?

**Comment by gschwend** [comment]
sure. next week

**Comment by gschwend** [comment]
UPDATE: 

There was an error in the product registry. Here it is the error message captured from the browser while trying to delete it: 

```
TypeError at /api/products/87/
expected str, bytes or os.PathLike object, not NoneType

Request Method: DELETE
Request URL: https://pz-server-dev.linea.org.br/api/products/87/
Django Version: 5.1.1
Python Executable: /usr/local/bin/uwsgi
Python Version: 3.10.16
Python Path: ['/app/attribute-maps', '/app', '.', '', '/usr/local/lib/python310.zip', '/usr/local/lib/python3.10', '/usr/local/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/site-packages/setuptools/_vendor']
Server time: Mon, 16 Dec 2024 20:10:14 +0000
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'django_celery_beat',
 'django_celery_results',
 'django_filters',
 'rest_framework',
 'drf_spectacular',
 'rest_framework.authtoken',
 'oauth2_provider',
 'social_django',
 'drf_social_oauth2',
 'djangosaml2',
 'core']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'djangosaml2.middleware.SamlSessionMiddleware']


Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/core/views/product.py", line 334, in destroy
    return super(ProductViewSet, self).destroy(request, pk, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/app/core/models/product.py", line 60, in delete
    product_path = pathlib.Path(settings.MEDIA_ROOT, self.path)
  File "/usr/local/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/local/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)

Exception Type: TypeError at /api/products/87/
Exception Value: expected str, bytes or os.PathLike object, not NoneType
Raised during: core.views.product.ProductViewSet
Request information:
USER: gschwend

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES:
saml_session = '63a6us39057olfqe734tyl6joskeh9qn'
_ga = 'GA1.1.596402007.1734379019'
_ga_H0212H45VM = 'GS1.1.1734379018.1.1.1734379054.0.0.0'
_ga_9VJLXT989W = 'GS1.1.1734379054.1.1.1734379337.0.0.0'
pzserver.csrftoken = '********************'
sessionid = '********************'
pzserver.access_token = '********************'
pzserver.refresh_token = '********************'

META:
CONTENT_LENGTH = ''
CONTENT_TYPE = ''
CSRF_COOKIE = 'jwx5DprdTLgMRBUcC1b2zte4xFJlcfWk'
DOCUMENT_ROOT = '/etc/nginx/html'
HTTP_ACCEPT = 'application/json'
HTTP_ACCEPT_ENCODING = 'gzip, deflate, br, zstd'
HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7'
HTTP_AUTHORIZATION = 'Bearer H2risJfaNCxvN0VJUTpoFSmEBd44Yn'
HTTP_CONNECTION = 'close'
HTTP_COOKIE = '********************'
HTTP_HOST = 'pz-server-dev.linea.org.br'
HTTP_ORIGIN = 'https://pz-server-dev.linea.org.br'
HTTP_REFERER = 'https://pz-server-dev.linea.org.br/user_products'
HTTP_SEC_CH_UA = '"Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"'
HTTP_SEC_CH_UA_MOBILE = '?0'
HTTP_SEC_CH_UA_PLATFORM = '"Linux"'
HTTP_SEC_FETCH_DEST = 'empty'
HTTP_SEC_FETCH_MODE = 'cors'
HTTP_SEC_FETCH_SITE = 'same-origin'
HTTP_USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
HTTP_X_FORWARDED_FOR = '191.181.56.221'
HTTP_X_FORWARDED_PROTO = 'https'
HTTP_X_REAL_IP = '191.181.56.221'
PATH_INFO = '/api/products/87/'
QUERY_STRING = ''
REMOTE_ADDR = '186.232.60.25'
REMOTE_PORT = '52360'
REQUEST_METHOD = 'DELETE'
REQUEST_SCHEME = 'http'
REQUEST_URI = '/api/products/87/'
SCRIPT_NAME = ''
SERVER_NAME = ''
SERVER_PORT = '8080'
SERVER_PROTOCOL = 'HTTP/1.0'
uwsgi.node = b'bcb5a478bf83'
uwsgi.version = b'2.0.26'
wsgi.errors = <_io.TextIOWrapper name=2 mode='w' encoding='UTF-8'>
wsgi.file_wrapper = <built-in function uwsgi_sendfile>
wsgi.input = <uwsgi._Input object at 0x7ff80e942730>
wsgi.multiprocess = False
wsgi.multithread = False
wsgi.run_once = False
wsgi.url_scheme = 'https'
wsgi.version = '(1, 0)'

Settings:
Using settings module pzserver.settings
ABSOLUTE_URL_OVERRIDES = {}
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
ADMINS = []
ALLOWED_HOSTS = ['pz-server-dev.linea.org.br']
AMQP_HOST = 'srvorch-dev.l2.linea.org.br'
AMQP_PASS = '********************'
AMQP_PORT = '5672'
AMQP_USER = 'orcadmin'
AMQP_VHOST = '/'
APPEND_SLASH = False
AUTHENTICATION_BACKENDS = "('drf_social_oauth2.backends.DjangoOAuth2', 'django.contrib.auth.backends.ModelBackend', 'core.saml2.ModifiedSaml2Backend')"
AUTH_PASSWORD_VALIDATORS = '********************'
AUTH_USER_MODEL = 'auth.User'
BASE_DIR = '/app'
CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_KEY_PREFIX = '********************'
CACHE_MIDDLEWARE_SECONDS = 600
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_URL = 'amqp://orcadmin:adminorc@srvorch-dev.l2.linea.org.br:5672/'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_RESULT_EXTENDED = True
CELERY_TASK_TIME_LIMIT = 1800
CELERY_TASK_TRACK_STARTED = True
CELERY_TIMEZONE = 'UTC'
CERT_DIR = '/saml2/certificates'
CSRF_COOKIE_AGE = 31449600
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_NAME = 'pzserver.csrftoken'
CSRF_COOKIE_PATH = '/'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = ['https://pz-server-dev.linea.org.br']
CSRF_USE_SESSIONS = False
DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2', 'NAME': 'pz_server_dev', 'USER': 'adm_pzdev', 'PASSWORD': '********************', 'HOST': 'desdb4.linea.org.br', 'PORT': '5432', 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'CONN_HEALTH_CHECKS': False, 'OPTIONS': {}, 'TIME_ZONE': None, 'TEST': {'CHARSET': None, 'COLLATION': None, 'MIGRATE': True, 'MIRROR': None, 'NAME': None}}}
DATABASE_ROUTERS = []
DATASETS_DIR = '/lustre/t1/apps/app.orch/datasets'
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
DATA_UPLOAD_MAX_NUMBER_FILES = 100
DATETIME_FORMAT = 'N j, Y, P'
DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M']
DATE_FORMAT = 'N j, Y'
DATE_INPUT_FORMATS = ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y']
DEBUG = 1
DEBUG_PROPAGATE_EXCEPTIONS = False
DECIMAL_SEPARATOR = '.'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_CHARSET = 'utf-8'
DEFAULT_EXCEPTION_REPORTER = 'django.views.debug.ExceptionReporter'
DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FROM_EMAIL = 'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE = ''
DEFAULT_TABLESPACE = ''
DISALLOWED_USER_AGENTS = []
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_HOST_PASSWORD = '********************'
EMAIL_HOST_USER = ''
EMAIL_PORT = 25
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = '********************'
EMAIL_SUBJECT_PREFIX = '[Django] '
EMAIL_TIMEOUT = None
EMAIL_USE_LOCALTIME = False
EMAIL_USE_SSL = False
EMAIL_USE_TLS = False
ENCRYP_CERT_PEM = '/saml2/cert/sp-cert.pem'
ENCRYP_KEY_PEM = '********************'
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None
FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
FILE_UPLOAD_PERMISSIONS = 420
FILE_UPLOAD_TEMP_DIR = None
FIRST_DAY_OF_WEEK = 0
FIXTURE_DIRS = []
FORCE_SCRIPT_NAME = None
FORMAT_MODULE_PATH = None
FORMS_URLFIELD_ASSUME_HTTPS = False
FORM_RENDERER = 'django.forms.renderers.DjangoTemplates'
FQDN = 'https://pz-server-dev.linea.org.br'
IGNORABLE_404_URLS = []
INSTALLED_APPS = ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'corsheaders', 'django_celery_beat', 'django_celery_results', 'django_filters', 'rest_framework', 'drf_spectacular', 'rest_framework.authtoken', 'oauth2_provider', 'social_django', 'drf_social_oauth2', 'djangosaml2', 'core']
INTERNAL_IPS = []
JSON_EDITOR = True
LANGUAGES = [('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI = ['he', 'ar', 'ar-dz', 'ckb', 'fa', 'ug', 'ur']
LANGUAGE_CODE = 'en-us'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_SAMESITE = None
LANGUAGE_COOKIE_SECURE = False
LOCALE_PATHS = []
LOGGING = {'version': 1, 'disable_existing_loggers': False, 'formatters': {'standard': {'format': '%(asctime)s [%(levelname)s] %(message)s'}}, 'handlers': {'default': {'level': 'DEBUG', 'class': 'logging.handlers.RotatingFileHandler', 'filename': '/archive/log/django.log', 'maxBytes': 5242880, 'backupCount': 5, 'formatter': 'standard'}, 'db_handler': {'level': 'DEBUG', 'class': 'logging.handlers.RotatingFileHandler', 'filename': '/archive/log/django_db.log', 'maxBytes': 5242880, 'backupCount': 5, 'formatter': 'standard'}, 'oauthlib': {'level': 'DEBUG', 'class': 'logging.handlers.RotatingFileHandler', 'filename': '/archive/log/oauthlib.log', 'maxBytes': 5242880, 'backupCount': 5, 'formatter': 'standard'}, 'saml': {'level': 'DEBUG', 'class': 'logging.handlers.RotatingFileHandler', 'filename': '/archive/log/saml2.log', 'maxBytes': 5242880, 'backupCount': 5, 'formatter': 'standard'}, 'products': {'level': 'DEBUG', 'class': 'logging.handlers.RotatingFileHandler', 'filename': '/archive/log/products.log', 'maxBytes': 5242880, 'backupCount': 5, 'formatter': 'standard'}}, 'loggers': {'django': {'handlers': ['default'], 'level': 'DEBUG', 'propagate': True}, 'django.db.backends': {'handlers': ['db_handler'], 'level': 'DEBUG', 'propagate': False}, 'oauthlib': {'handlers': ['oauthlib'], 'level': 'DEBUG', 'propagate': True}, 'saml': {'handlers': ['saml'], 'level': 'DEBUG', 'propagate': True}, 'products': {'handlers': ['products'], 'level': 'DEBUG', 'propagate': True}}}
LOGGING_CONFIG = 'logging.config.dictConfig'
LOGGING_LEVEL = 'DEBUG'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/saml2/login/'
LOGOUT_REDIRECT_URL = None
LOG_DIR = '/archive/log'
MANAGERS = []
MEDIA_ROOT = '/archive/data/'
MEDIA_URL = '/archive/data/'
MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
METADATAS = ['https://www.linea.org.br/metadata/satosa-dev-frontend-github.xml', 'https://www.linea.org.br/metadata/satosa-dev-frontend-rubin.xml']
METADATA_URLS = [{'url': 'https://www.linea.org.br/metadata/satosa-dev-frontend-github.xml', 'cert': None}, {'url': 'https://www.linea.org.br/metadata/satosa-dev-frontend-rubin.xml', 'cert': None}]
MIDDLEWARE = ['django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'corsheaders.middleware.CorsMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'djangosaml2.middleware.SamlSessionMiddleware']
MIGRATION_MODULES = {}
MONTH_DAY_FORMAT = 'F j'
NUMBER_GROUPING = 0
OAUTH2_PROVIDER = {'ACCESS_TOKEN_EXPIRE_SECONDS': '********************'}
ORCHEST_CLIENT_ID = '9YdgVqubnTpHZlXN1UNPR91P5kQTVO3sgmOKeSMK'
ORCHEST_CLIENT_SECRET = '********************'
ORCHEST_URL = 'http://srvorch-dev.l2.linea.org.br:8088'
PASSWORD_HASHERS = '********************'
PASSWORD_RESET_TIMEOUT = '********************'
PIPELINES_DIR = '/lustre/t1/apps/app.orch/dev/pipelines'
PREPEND_WWW = False
PROCESSING_DIR = '/lustre/t1/apps/app.orch/dev/processes'
REST_FRAMEWORK = {'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', 'DEFAULT_AUTHENTICATION_CLASSES': ('oauth2_provider.contrib.rest_framework.OAuth2Authentication', 'drf_social_oauth2.authentication.SocialAuthentication', 'rest_framework.authentication.TokenAuthentication', 'rest_framework.authentication.SessionAuthentication'), 'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',), 'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend', 'rest_framework.filters.SearchFilter', 'rest_framework.filters.OrderingFilter'], 'DEFAULT_PAGINATION_CLASS': 'core.pagination.CustomPageNumberPagination', 'DEFAULT_METADATA_CLASS': 'core.SimpleMetadataWithFilters', 'PAGE_SIZE': 100, 'TEST_REQUEST_DEFAULT_FORMAT': 'json'}
ROOT_URLCONF = 'pzserver.urls'
SAML_ATTRIBUTE_MAPPING = {'eduPersonUniqueId': ('username',), 'sn': ('full_name',), 'isMemberOf': ('name',), 'email': ('email',)}
SAML_CONFIG = {'xmlsec_binary': '/usr/bin/xmlsec1', 'entityid': 'https://pz-server-dev.linea.org.br/saml2/metadata/', 'attribute_map_dir': '/app/attribute-maps', 'description': 'SP Pz Server', 'service': {'sp': {'name': 'sp_pzserver', 'ui_info': {'display_name': {'text': 'SP Pz', 'lang': 'en'}, 'description': {'text': 'Pz Service Provider', 'lang': 'en'}, 'information_url': {'text': 'https://pz-server-dev.linea.org.br/about', 'lang': 'en'}, 'privacy_statement_url': {'text': 'https://pz-server-dev.linea.org.br', 'lang': 'en'}}, 'name_id_format': ['urn:oasis:names:tc:SAML:2.0:nameid-format:persistent', 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'], 'endpoints': {'assertion_consumer_service': [('https://pz-server-dev.linea.org.br/saml2/acs/', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST')], 'single_logout_service': [('https://pz-server-dev.linea.org.br/saml2/ls/', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'), ('https://pz-server-dev.linea.org.br/saml2/ls/post', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST')]}, 'force_authn': False, 'name_id_format_allow_create': False, 'want_response_signed': True, 'authn_requests_signed': True, 'want_assertions_signed': False, 'only_use_keys_in_metadata': '********************', 'allow_unsolicited': False}}, 'metadata': {'remote': [{'url': 'https://www.linea.org.br/metadata/satosa-dev-frontend-github.xml', 'cert': None}, {'url': 'https://www.linea.org.br/metadata/satosa-dev-frontend-rubin.xml', 'cert': None}]}, 'debug': '1', 'key_file': '********************', 'cert_file': '/saml2/cert/sp-cert.pem', 'encryption_keypairs': '********************', 'contact_person': [{'given_name': 'LIneA', 'sur_name': 'Team', 'company': 'LIneA', 'email_address': 'itteam@linea.org.br', 'contact_type': 'technical'}], 'organization': {'name': [('LIneA', 'pt-br')], 'display_name': [('LIneA', 'pt-br')], 'url': [('https://linea.org.br/', 'pt-br')]}}
SAML_CREATE_UNKNOWN_USER = True
SAML_CSP_HANDLER = ''
SAML_DEFAULT_BINDING = 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
SAML_IGNORE_LOGOUT_ERRORS = True
SAML_SESSION_COOKIE_NAME = 'saml_session'
SECRET_KEY = '********************'
SECRET_KEY_FALLBACKS = '********************'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_HSTS_SECONDS = 0
SECURE_PROXY_SSL_HEADER = None
SECURE_REDIRECT_EXEMPT = []
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_SSL_HOST = None
SECURE_SSL_REDIRECT = False
SERVER_EMAIL = 'root@localhost'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_FILE_PATH = None
SESSION_SAVE_EVERY_REQUEST = False
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE = 'pzserver.settings'
SHORT_DATETIME_FORMAT = 'm/d/Y P'
SHORT_DATE_FORMAT = 'm/d/Y'
SIGNING_BACKEND = 'django.core.signing.TimestampSigner'
SIG_CERT_PEM = '/saml2/cert/sp-cert.pem'
SIG_KEY_PEM = '********************'
SILENCED_SYSTEM_CHECKS = []
SPECTACULAR_SETTINGS = {'TITLE': 'Photo-z Server API', 'DESCRIPTION': 'This is the API for the Photo-z Server.', 'VERSION': '0.1.0'}
STATICFILES_DIRS = []
STATICFILES_FINDERS = ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATIC_ROOT = '/app/django_static'
STATIC_URL = '/django_static/'
STORAGES = {'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'}, 'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'}}
TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages', 'social_django.context_processors.backends', 'social_django.context_processors.login_redirect']}}]
TEST_NON_SERIALIZED_APPS = []
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR = ','
TIME_FORMAT = 'P'
TIME_INPUT_FORMATS = ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE = 'UTC'
UPLOAD_DIR = '/lustre/t1/apps/app.pzserver/dev/uploads'
USE_I18N = True
USE_THOUSAND_SEPARATOR = False
USE_TZ = True
USE_X_FORWARDED_HOST = False
USE_X_FORWARDED_PORT = False
WSGI_APPLICATION = 'pzserver.wsgi.application'
X_FRAME_OPTIONS = 'DENY'
YEAR_MONTH_FORMAT = 'F Y'


You’re seeing this error because you have DEBUG = True in your
Django settings file. Change that to False, and Django will
display a standard page generated by the handler for this status code.
```

**Comment by crisingulani** [comment]
There was an error registering the product, see how it looks in the database: `None/random_sample_truth_type_1_0.002.parquet`. Record deleted manually.
